
# This file is used to configure the Supabase project

project_id = "mwgnpexeymgpzibnkiof"

[api]
# Port to start the API server on
port = 54321
# Schemas to expose in your API
schemas = ["public", "storage"]

[db]
# Port to start the DB server on
port = 54322

[functions]
[functions.create_user_profile]
verify_jwt = true

[functions.fatsecret-search]
verify_jwt = true

[functions.create-paypal-subscription]
verify_jwt = true

[functions.verify-paypal-payment]
verify_jwt = true

[functions.paypal-webhook]
verify_jwt = false

[functions.revise-paypal-subscription]
verify_jwt = true

[functions.suspend-paypal-subscription]
verify_jwt = true

[functions.activate-paypal-subscription]
verify_jwt = true

[functions.cancel-paypal-subscription]
verify_jwt = true

[functions.retry-paypal-payment]
verify_jwt = true

[functions.check-expired-grace-periods]
verify_jwt = false

[functions.send-support-email]
verify_jwt = true

[functions.auth-send-email]
enabled = true
verify_jwt = true
import_map = "./functions/auth-send-email/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/auth-send-email/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/auth-send-email/*.html" ]
