// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { Http } from '@capacitor-community/http';
import { Capacitor } from '@capacitor/core';

const SUPABASE_URL = "https://mwgnpexeymgpzibnkiof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13Z25wZXhleW1ncHppYm5raW9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNDMxMDAsImV4cCI6MjA2MjcxOTEwMH0.4MCeBc9YPSI4ASDcSLrz_25R70KmRBEfyEtqmsZ3GYY";

// Custom fetch function - try fetch first, use CapacitorHttp only on network errors
const customFetch = async (url: string, options?: RequestInit): Promise<Response> => {
  const platform = Capacitor.getPlatform();
  const isNative = platform === 'ios' || platform === 'android';
  
  // Helper function to fetch with timeout
  const fetchWithTimeout = (url: string, options: RequestInit | undefined, timeoutMs: number) => {
    return Promise.race([
      fetch(url, options),
      new Promise<Response>((_, reject) =>
        setTimeout(() => reject(new Error('Network timeout after ' + timeoutMs + 'ms')), timeoutMs)
      ),
    ]);
  };
  
  // Always try fetch first - it's more reliable
  try {
    console.log(`🌐 [Fetch] ${(options?.method || 'GET').toUpperCase()} ${url}`);
    const response = await fetchWithTimeout(url, options, 15000); // 15 second timeout
    console.log(`✅ [Fetch] Status ${response.status}`);
    return response;
  } catch (fetchError: any) {
    console.error(`❌ [Fetch] Failed:`, fetchError.message);
    
    // Only try CapacitorHttp on native platforms if fetch fails
    if (isNative) {
      try {
        console.log(`🔄 [CapacitorHttp] Fallback to native HTTP...`);
        
        const method = (options?.method || 'GET').toUpperCase() as any;
        const headers = (options?.headers as Record<string, string>) || {};
        
        let body: any;
        if (options?.body) {
          if (typeof options.body === 'string') {
            try {
              body = JSON.parse(options.body);
            } catch {
              body = options.body;
            }
          } else {
            body = options.body;
          }
        }
        
        console.log(`🌐 [CapacitorHttp] ${method} ${url}`);
        
        const response = await Http.request({
          url,
          method,
          headers,
          data: body,
          readTimeout: 15000,
          connectTimeout: 15000,
        });
        
        console.log(`✅ [CapacitorHttp] Status ${response.status}`);
        
        // Convert CapacitorHttp response to Web Fetch API Response
        const responseBody = typeof response.data === 'string' ? response.data : JSON.stringify(response.data);
        
        return new Response(responseBody, {
          status: response.status,
          statusText: response.status === 200 ? 'OK' : `HTTP ${response.status}`,
          headers: new Headers(response.headers as Record<string, string>),
        });
      } catch (httpError: any) {
        console.error(`❌ [CapacitorHttp] Also failed:`, httpError.message);
        throw httpError;
      }
    } else {
      // On web, if fetch fails, just throw
      throw fetchError;
    }
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: customFetch,
  },
});